import type { StudioState } from "./types";

export const initialState: StudioState = {
  step: 1,
  maxStepReached: 1,
  sourceType: null,
  selectedAdId: null,
  selectedAdVideoUrl: null,
  selectedAdBrand: null,
  uploadedVideoUrl: null,
  uploadedVideoFile: null,
  providedScript: "",
  frames: [],
  analysis: null,
  isAnalyzing: false,
  analyzeError: null,
  audioExtracted: null,
  productImage: null,
  productImages: [],
  creatorImage: null,
  creatorImages: [],
  bigIdea: "",
  productInfo: "",
  targetAudience: "",
  landingPageUrls: [""],
  isScrapingUrls: false,
  motivator: "",
  emotionalTone: "",
  storylineType: "",
  scriptScenes: [],
  isGeneratingScript: false,
  scriptError: null,
  scenes: [],
  isGeneratingStoryboard: false,
  storyboardError: null,
  aspectRatio: "9:16",
  voice: "Kore",
  voiceSource: "gemini",
  voiceName: "Kore",
  imageModel: "kie",
  videoModel: "kie",
  productVidtoryUrl: null,
  creatorVidtoryUrl: null,
  currentProjectId: null,
  currentProjectName: null,
};
